name: kyons_melos
repository: https://github.com/Kyons-VN/kyons-melos

packages:
  - packages/*
  - packages/*/*
  - packages/*/*/*
  - tests

ignore:
  - packages/**/example

ide:
  intellij:
    enabled: false

scripts:
  analyze:
    exec: dart analyze .
