name: shared_package
version: 0.0.1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: 3.13.9

dependencies:
  flutter:
    sdk: flutter

  another_flushbar: 1.12.30
  intl: 0.18.1
  flutter_adaptive_scaffold: 0.1.7+1
  flutter_animate: 4.2.0+1
  flutter_hooks: 0.20.3
  flutter_html: 3.0.0-beta.2
  flutter_svg: 2.0.8
  fpdart: 1.1.0
  freezed_annotation: 2.4.1
  google_fonts: 6.1.0
  json_annotation: 4.8.1

dev_dependencies:
  build_runner: null
  flutter_lints: 3.0.0
  flutter_test:
    sdk: flutter
  freezed: 2.4.5
  json_serializable: 6.7.1

flutter:
  uses-material-design: true

  generate: true

  assets:
    - assets/images/
    - assets/music/
    - assets/sfx/
    - assets/google_fonts/
    - assets/kyons_fonts/

  fonts:
    - family: Permanent Marker
      fonts:
        - asset: assets/Permanent_Marker/PermanentMarker-Regular.ttf
    - family: Kyons-Icon-Fonts
      fonts:
        - asset: assets/kyons_fonts/Kyons-Icon-Fonts.ttf
