name: shared_package
version: 0.0.1

environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: 3.7.1

dependencies:
  another_flushbar: 1.12.29
  dio: 4.0.6
  fimber: ^0.6.6
  flutter:
    sdk: flutter
  flutter_hooks: 0.18.5+1
  flutter_html: 3.0.0-alpha.5
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: 7.0.1
  flutter_svg: 1.1.5
  fpdart: 0.4.0
  freezed_annotation: 2.2.0
  games_services: 2.0.8
  go_router: 6.0.4
  google_fonts: 4.0.3
  hooks_riverpod: 1.0.4
  intl: 0.17.0
  json_annotation: 4.8.0
  logging: 1.1.1
  scrollable_positioned_list: 0.3.5
  shared_preferences: 2.0.17
  url_launcher: 6.1.9
  uuid: 3.0.7

dev_dependencies:
  build_runner: null

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter
  freezed: 2.3.2
  # injectable_generator: 1.5.3
  json_serializable: 6.6.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    - assets/images/
    - assets/music/
    - assets/sfx/
    - assets/google_fonts/
    - assets/kyons_fonts/

  fonts:
    - family: Permanent Marker
      fonts:
        - asset: assets/Permanent_Marker/PermanentMarker-Regular.ttf
    - family: Kyons Icons
      fonts:
        - asset: assets/kyons_fonts/KyonsIcons.ttf
# flutter_icons:
# android: true
# ios: true
# image_path: "assets/icon.png"
# adaptive_icon_background: "#2C3D5B"
# adaptive_icon_foreground: "assets/icon-adaptive-foreground.png"
# windows:
#   generate: true
#   image_path: "assets/icon.png"
