name: shared_package
version: 0.0.1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: 3.7.10

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  another_flushbar: 1.12.30
  dio: 5.1.2
  fimber: 0.6.6
  flutter_adaptive_scaffold: 0.1.3
  flutter_animate: 4.1.0
  flutter_hooks: 0.18.6
  flutter_html: 3.0.0-alpha.5
  flutter_inappwebview: 5.7.2+3
  flutter_secure_storage: 8.0.0
  flutter_svg: 2.0.7
  fpdart: 0.6.0
  freezed_annotation: 2.2.0
  go_router: 6.4.1
  google_fonts: 4.0.4
  hooks_riverpod: 2.3.6
  image_picker: 0.8.7+5
  intl: 0.18.0
  json_annotation: 4.8.1
  logging: 1.1.1
  riverpod_annotation: 2.1.1
  scrollable_positioned_list: 0.3.8
  share_plus: 7.0.0
  shared_preferences: 2.1.1
  url_launcher: 6.1.11
  uuid: 3.0.7
# shared_package:
#     path: ../shared_package
#
dev_dependencies:
  build_runner: null
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter
  freezed: 2.3.3
  json_serializable: 6.6.2
  riverpod_generator: 2.2.1

flutter:
  uses-material-design: true

  generate: true

  assets:
    - assets/images/
    - assets/music/
    - assets/sfx/
    - assets/google_fonts/
    - assets/kyons_fonts/

  fonts:
    - family: Permanent Marker
      fonts:
        - asset: assets/Permanent_Marker/PermanentMarker-Regular.ttf
    - family: Kyons-Icon-Fonts
      fonts:
        - asset: assets/kyons_fonts/Kyons-Icon-Fonts.ttf
