name: shared_package
version: 0.0.1

environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: 3.7.1

dependencies:
  another_flushbar: 1.12.29
  dio: 4.0.6
  fimber: ^0.6.6
  flutter:
    sdk: flutter
  flutter_hooks: 0.18.5+1
  flutter_html: 3.0.0-alpha.5
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: 7.0.1
  flutter_svg: 1.1.5
  fpdart: 0.4.0
  freezed_annotation: 2.2.0
  games_services: 2.0.8
  go_router: 6.0.4
  google_fonts: 4.0.3
  hooks_riverpod: 1.0.4
  intl: 0.17.0
  json_annotation: 4.8.0
  logging: 1.1.1
  scrollable_positioned_list: 0.3.5
  shared_preferences: 2.0.17
  url_launcher: 6.1.9
  uuid: 3.0.7

dev_dependencies:
  build_runner: null

  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter
  freezed: 2.3.2
  json_serializable: 6.6.1

flutter:
  uses-material-design: true

  generate: true

  assets:
    - assets/images/
    - assets/music/
    - assets/sfx/
    - assets/google_fonts/
    - assets/kyons_fonts/

  fonts:
    - family: Permanent Marker
      fonts:
        - asset: assets/Permanent_Marker/PermanentMarker-Regular.ttf
    - family: Kyons Icons
      fonts:
        - asset: assets/kyons_fonts/KyonsIcons.ttf
